#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/276c7ca1-99e1-4271-8abc-8a89e071ee59 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudSmartPlug enchufe1;
  CloudSmartPlug enchufe2;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"


void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  pinMode(16, OUTPUT);
  pinMode(5, OUTPUT);
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 

}



/*
  Since Enchufe1 is READ_WRITE variable, onEnchufe1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onEnchufe1Change()  {
  // Add your code here to act upon Enchufe1 change
  if (enchufe1 == 1) {
    digitalWrite(16, HIGH);
  } else if (enchufe1 == 0) {
    digitalWrite(16, LOW);
  }
}

/*
  Since Enchufe2 is READ_WRITE variable, onEnchufe2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onEnchufe2Change()  {
  // Add your code here to act upon Enchufe2 change
    if (enchufe2 == 1) {
    digitalWrite(5, HIGH);
  } else if (enchufe2 == 0) {
    digitalWrite(5, LOW);
  }
}